import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';

/// Service to handle report generation and saving
class ReportService {
  /// Save analysis report to device storage
  Future<String> saveReport({
    required Map<String, dynamic> analysisResult,
    required String imagePath,
  }) async {
    try {
      // Get the documents directory
      final directory = await getApplicationDocumentsDirectory();
      
      // Create reports subdirectory if it doesn't exist
      final reportsDir = Directory('${directory.path}/drishti_reports');
      if (!await reportsDir.exists()) {
        await reportsDir.create(recursive: true);
      }

      // Generate filename with timestamp
      final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
      final filename = 'TB_Analysis_Report_$timestamp.txt';
      final filePath = '${reportsDir.path}/$filename';

      // Create report content
      final reportContent = _generateReportContent(analysisResult, imagePath);

      // Write to file
      final file = File(filePath);
      await file.writeAsString(reportContent);

      return filePath;
    } catch (e) {
      print('Error saving report: $e');
      rethrow;
    }
  }

  /// Generate formatted report content
  String _generateReportContent(
    Map<String, dynamic> result,
    String imagePath,
  ) {
    final buffer = StringBuffer();
    
    buffer.writeln('═══════════════════════════════════════════════════════');
    buffer.writeln('           PROJECT DRISHTI - TB ANALYSIS REPORT         ');
    buffer.writeln('═══════════════════════════════════════════════════════');
    buffer.writeln();
    
    buffer.writeln('Report Generated: ${DateFormat('MMMM dd, yyyy - HH:mm:ss').format(DateTime.now())}');
    buffer.writeln();
    
    buffer.writeln('───────────────────────────────────────────────────────');
    buffer.writeln('IMAGE INFORMATION');
    buffer.writeln('───────────────────────────────────────────────────────');
    buffer.writeln('Source: $imagePath');
    buffer.writeln();
    
    buffer.writeln('───────────────────────────────────────────────────────');
    buffer.writeln('ANALYSIS RESULTS');
    buffer.writeln('───────────────────────────────────────────────────────');
    
    final probability = result['probability'] as double;
    final riskLevel = result['riskLevel'] as String;
    final confidence = result['confidence'] as double;
    
    buffer.writeln('TB Probability:    ${(probability * 100).toStringAsFixed(2)}%');
    buffer.writeln('Risk Level:        $riskLevel');
    buffer.writeln('Confidence Score:  ${(confidence * 100).toStringAsFixed(2)}%');
    buffer.writeln();
    
    buffer.writeln('───────────────────────────────────────────────────────');
    buffer.writeln('INTERPRETATION');
    buffer.writeln('───────────────────────────────────────────────────────');
    
    if (probability >= 0.7) {
      buffer.writeln('⚠ HIGH RISK: The analysis indicates a high probability');
      buffer.writeln('of TB presence. Immediate medical consultation is');
      buffer.writeln('strongly recommended.');
    } else if (probability >= 0.4) {
      buffer.writeln('⚠ MEDIUM RISK: The analysis shows moderate indicators');
      buffer.writeln('of TB. Medical evaluation is recommended for confirmation.');
    } else {
      buffer.writeln('✓ LOW RISK: The analysis suggests low probability of TB.');
      buffer.writeln('Regular health monitoring is advised.');
    }
    
    buffer.writeln();
    buffer.writeln('───────────────────────────────────────────────────────');
    buffer.writeln('DISCLAIMER');
    buffer.writeln('───────────────────────────────────────────────────────');
    buffer.writeln('This report is generated by an AI-assisted tool and');
    buffer.writeln('should not be considered as a definitive medical diagnosis.');
    buffer.writeln('Please consult with a qualified healthcare professional');
    buffer.writeln('for proper medical evaluation and treatment.');
    buffer.writeln();
    buffer.writeln('═══════════════════════════════════════════════════════');
    buffer.writeln('              End of Report - Project Drishti           ');
    buffer.writeln('═══════════════════════════════════════════════════════');
    
    return buffer.toString();
  }
}
